---
title: Installeer en gebruik Visual Studio Code met Unity
hero_image: images/banner.png
description: Installeer en gebruik Visual Studio Code met Unity
version: 1
listed: false
copyedit: false
last_tested: "2023-07-24"
steps:
  - title: Unity en Visual Studio-code
