title: Install and use Visual Studio Code with Unity
hero_image: images/banner.png
description: Install and use Visual Studio Code with Unity
version: 1
listed: false
copyedit: false
last_tested: "2023-07-24"
steps:
  - title: Unity and Visual Studio