title: قم بتثبيت و استخدام شفرة الاستوديو المرئي مع الوحدة
hero_image: images/banner.png
description: قم بتثبيت و استخدام شفرة الاستوديو المرئي مع الوحدة
version: 1
listed: false
copyedit: false
last_tested: "2023-07-24"
steps:
  - 
    title: الوحدة و شفرة الاستوديو المرئي
